#注册接口

POST http://localhost:9202/register/registerByPhone
Content-Type: application/x-www-form-urlencoded

phoneNumber=12345678&password=123456

###登录接口
POST http://127.0.0.1:9202/uc/login/login
Content-Type: application/x-www-form-urlencoded

phoneNumber=123456&password=123456

###获取用户信息
POST http://localhost:9202/uc/uCenter/getUserInfo
Content-Type: application/x-www-form-urlencoded
x-auth-token: 52c30f09-0a9b-4c81-97f5-5781fc364d26

userId=1163690799456124930

####获取用户信息
POST http://localhost:9202/uc/uCenter/hello
Content-Type: application/x-www-form-urlencoded
x-auth-token: efa739f5-2092-4550-8a78-56a3e31bed7e

###新增用户标签
POST http://localhost:9202/uc/tag/customerAdd
Content-Type: application/x-www-form-urlencoded
x-auth-token: 85903636-67b6-43e7-8967-81e0a9245b8b

tagName=livepool fc&tagComment="利物浦足球俱乐部"&nickName="红军,利物浦"

###