#注册接口

POST http://localhost:9202/uc/register/registerByPhone
Content-Type: application/x-www-form-urlencoded

phoneNumber=13579&password=123456

###登录接口
POST http://127.0.0.1:9202//uc/login/login
Content-Type: application/x-www-form-urlencoded

phoneNumber=123456&password=123456

### 添加好友
GET http://localhost:9202/uc/user/newFriendRequest?retrieveInfo=13579
Content-Type: application/x-www-form-urlencoded
x-auth-token: 348c6c97-bb7f-46ca-8a30-d406c74ab465
###获取用户信息
POST http://localhost:9202/uc/user/getUserInfo
Content-Type: application/x-www-form-urlencoded
x-auth-token: 99fd4044-3a90-4437-a1be-14967b1dcdf6

userId=1163690799456124930

####获取用户信息
POST http://localhost:9202/uc/uCenter/hello
Content-Type: application/x-www-form-urlencoded
x-auth-token: efa739f5-2092-4550-8a78-56a3e31bed7e

###新增用户标签
POST http://localhost:9202/uc/tag/customerAdd
Content-Type: application/x-www-form-urlencoded
x-auth-token: 0cc8484b-7a41-4b07-98dc-30fb2995fd2d

interestTag=旅游&comment="旅游"

###
GET http://localhost:9202/uc/tag/interestInTag?tagName=旅游
Content-Type: application/x-www-form-urlencoded
x-auth-token: 6a713e35-1160-4963-884a-0d082d1c3458



###