server:
  port: 9201
#server.context-path=/gapi

spring:
  application:
    name: gateway
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      #路由配置
      routes:
      - id: ucenter
        uri: http://localhost:9202
        predicates:
        - Path=/a/**
      - id: community
        uri: http://localhost:9205
        predicates:
        - Path=/a/**
#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9200/eureka/
    discovery:
      locator:
        enabled: true

#ribbon超时设置
#ReadTimeout 设置路由转发请求的时候，创建请求连接的超时时间
#ConnectTimeout 用来设置路由转发请求的超时时间
#ribbon:
#  ReadTimeout: 5000
#  ConnectTimeout: 5000
#  MaxAutoRetries: 0
#  MaxAutoRetriesNextServer: 1

# test
#ucenter:
#  ribbon:
#    ReadTimeout: 11000
#    ConnectTimeout: 11000
#    MaxAutoRetries: 0
#    MaxAutoRetriesNextServer: 1
#    eureka:
#      enabled: true

#hystrix超时配置
#设置API网关中路由转发请求的HystrixCommand执行超时时间
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 10000
#    ucenter:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 10000
### zuul.routes 网管api配置
## zuul.ratelimit 限流配置
#限流类型：url、origin、user
#禁用一个 zuul.<SimpleClassName>.<filterType> .disable = true
#zuul:
#  routes:
#    uc:
#      serviceId: ucenter
#      path: /uc/**
#      stripPrefix: false
#      customSensitiveHeaders: true

###mybatis读写分离配置
#mybatis.mapperScanPackage=com.spark.bitrade.mapper.dao

##读写库分离配置
#mysql.datasource.write 写数据库配置
#url: jdbc:mysql://127.0.0.1:3306/test1?useUnicode=true&amp;characterEncoding=utf-8
# url: jdbc:mysql://127.0.0.1:3306/test2?useUnicode=true&amp;characterEncoding=utf-8

